# Generated by Django 4.2.4 on 2023-08-08 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textinput",
            name="text",
        ),
        migrations.AddField(
            model_name="textinput",
            name="url",
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
